version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
#  test:
#    build: .
#    environment:
#      - FLASK_ENV=test
#    command: ["pytest", "tests/"]
#    depends_on:
#      - redis
  redis:
    image: "redis:alpine"
